# ASDF setup...
# [[ -s '/usr/local/opt/asdf/asdf.sh' ]] && source '/usr/local/opt/asdf/asdf.sh'
# [[ -s '/usr/local/opt/asdf/completions/asdf.bash' ]] && source '/usr/local/opt/asdf/completions/asdf.bash'
