#!/usr/bin/env bash

# Mount the macOS installer...
hdiutil attach "/Applications/Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg" \
  -noverify -nobrowse -mountpoint /Volumes/esd

# Create an empty ISO file...
hdiutil create -o Sierra.cdr -size 6144m -layout SPUD -fs HFS+J

# Mount the empty ISO file...
hdiutil attach Sierra.cdr.dmg -noverify -nobrowse -mountpoint /Volumes/iso

# Copy installer contents...
asr restore -source /Volumes/esd/BaseSystem.dmg -target /Volumes/iso -noprompt -noverify -erase

# Remove invalid installer package link...
rm /Volumes/OS\ X\ Base\ System/System/Installation/Packages

# Copy installer package files...
cp -rp /Volumes/esd/Packages /Volumes/OS\ X\ Base\ System/System/Installation
cp -rp /Volumes/esd/BaseSystem.chunklist /Volumes/OS\ X\ Base\ System/
cp -rp /Volumes/esd/BaseSystem.dmg /Volumes/OS\ X\ Base\ System/

# Unmout temporary volumes...
hdiutil detach /Volumes/esd
hdiutil detach /Volumes/OS\ X\ Base\ System

# Process ISO image file...
hdiutil convert Sierra.cdr.dmg -format UDTO -o Sierra.iso

# Cleanup...
mv Sierra.iso.cdr Sierra.iso
rm Sierra.cdr.dmg

