#!/usr/bin/env bash

# http://www.insanelymac.com/forum/topic/325603-how-to-create-a-bootable-high-sierra-iso-for-vmware/
# https://tylermade.net/2017/10/05/how-to-create-a-bootable-iso-image-of-macos-10-13-high-sierra-installer/

# Create an empty ISO file...
hdiutil create -o /tmp/HighSierra.cdr -size 5130m -layout SPUD -fs HFS+J

# Mount the empty ISO file...
hdiutil attach /tmp/HighSierra.cdr.dmg -noverify -nobrowse -mountpoint /Volumes/iso

# Execute macOS installer command...
sudo /Applications/Install\ macOS\ High\ Sierra.app/Contents/Resources/createinstallmedia --volume /Volumes/iso

# Convert bootable image to ISO format...
hdiutil convert /tmp/HighSierra.cdr.dmg -format UDTO -o ~/Downloads/Operating\ Systems/macOS-High-Sierra.iso

# Cleanup...
hdiutil detach /Volumes/iso
mv ~/Downloads/Operating\ Systems/macOS-High-Sierra.iso.cdr ~/Downloads/Operating\ Systems/macOS-High-Sierra.iso
rm /tmp/HighSierra.cdr.dmg

